### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Kamyee0409** [alphaply/DouyinComments#10]
已替换cookies，并安装好对应的插件环境，跑出来0 comment：Fetching comments: 0comment [00:02, ?comment/s]
报错原因为：execjs._exceptions.ProgramError: SyntaxError: 缺少 ')'
是自己的环境配置出问题了？求解答~
<img width="794" alt="1" src="https://github.com/user-attachments/assets/fc12e0ea-c0dc-4071-aed0-136d71bd66f1">
<img width="830" alt="2" src="https://github.com/user-attachments/assets/4ac5a911-c3d4-4bc8-8aa4-a64888a182e9">

**Comment by alphaply** [comment]
nodejs安装了么？

**Comment by Kamyee0409** [comment]
> nodejs安装了么？

装了的，然后我重新安装node再跑一遍，还是这个结果，不知道是哪出错了TT

**Comment by alphaply** [comment]
视频id发一下

Kamyee0409 ***@***.***> 于 2024年10月25日周五 00:01写道：

**Comment by alphaply** [comment]
确定没有安装错么？
pip install httpx pandas PyExecJS

**Comment by Kamyee0409** [comment]
> 确定没有安装错么？ pip install httpx pandas PyExecJS
> 
> nodejs版本多少

感谢佬！后面自己找到错误了，原来是填错对应的cookies，麻烦了

**Comment by Kamyee0409** [comment]
评论条数正确，代码没报错，replies文件没问题，但comments文件打开变乱码了

**Comment by alphaply** [comment]
保存文件的时候自己修改编码即可

**Comment by Kamyee0409** [comment]
> 保存文件的时候自己修改编码即可

佬！上周按照你的方法成功写入了，但今天爬的时候发现，程序没报错，但是评论条数不对了，并且comment是乱码的，而reply是正常的。这怎么搞呢TT
![image](https://github.com/user-attachments/assets/d494dd07-ae58-4b30-a363-fc9ac066e273)
