### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by moreorlesshub** [alphaply/DouyinComments#11]
大佬为啥我这里只能获取一级评论，二级的获取不了

**Comment by moreorlesshub** [comment]
![Uploading Snipaste_2024-10-26_18-57-18.png…]()

**Comment by alphaply** [comment]
视频id发一下

**Comment by moreorlesshub** [comment]
> 视频id发一下

7429623066344312105

**Comment by alphaply** [comment]
Enter the aweme_id: 7429623066344312105
Fetching comments: 79comment [00:10,  7.56comment/s]
Found 79 comments.
Fetching replies: 100%|██████████| 79/79 [00:34<00:00,  2.30comment/s]
Found 48 replies
Found 127 in totals
done!

**Comment by moreorlesshub** [comment]
这是为啥，我重装了一下python，现在用的是3.1难道是这个原因吗

**Comment by moreorlesshub** [comment]
3.10

**Comment by alphaply** [comment]
我没有看见你的报错截图

**Comment by moreorlesshub** [comment]
> 我没有看见你的报错截图
![Snipaste_2024-10-28_17-08-55](https://github.com/user-attachments/assets/6ded62ab-9413-4c34-ba3d-d2aac1b42dbb)
![Snipaste_2024-10-28_17-09-06](https://github.com/user-attachments/assets/1c46f438-8be6-4ca9-b1b4-32dc66159963)

**Comment by alphaply** [comment]
cookie是否正确

**Comment by alphaply** [comment]
Enter the aweme_id: 7429623066344312105
Fetching comments: 90comment [00:09,  9.99comment/s]
Found 90 comments.
Fetching replies: 100%|██████████| 90/90 [00:34<00:00,  2.64comment/s]
Found 51 replies
Found 141 in totals
done!

**Comment by moreorlesshub** [comment]
cookie是这样的
cookie = "ttwid=1%7CatJbVPDlwIBTWC1ePATuuJsSraMe2-JmX8zZZG7upFc%7C1716370528%7C42a34b20efd699e697d393527bbca2fe2a26bd94855c0015b5c4b3cff8fc0f59; UIFID_TEMP=973a3fd64dcc46a3490fd9b60d4a8e663b34df4ccc4bbcf97643172fb712d8b09ffb141150f0dc9da20f60cf543525ddf8c3902495bf9f57a024eea1f723bf55b17a37061e90d71aa84ead33dda43dcc; douyin.com; device_web_cpu_core=12; device_web_memory_size=8; architecture=amd64; hevc_supported=true; csrf_session_id=cbef88d70cb238da152e9e8e4117f3b3; xgplayer_user_id=878267971490; odin_tt=4e9923480d4376f3f59d9b0fa432e435a58773f0a5afa873d82e1f1ded179aa7d8910f8dea932a9daba0df2354a3f71d22f84be7ee32fe2eb86c6b655157480a46d7954dcf0d3131423959ea21502d8e; fpk1=U2FsdGVkX19CArvOzCKs3VtAPGZcsx9+q5Ww1kjXGu/SA4uMspQ08uwSaai+Alktx0sZe2C/Y0PKp8P3NTQfQQ==; fpk2=362d7fe3d8b2581bffa359f0eeda7106; bd_ticket_guard_client_web_domain=2; UIFID=973a3fd64dcc46a3490fd9b60d4a8e663b34df4ccc4bbcf97643172fb712d8b09ffb141150f0dc9da20f60cf543525dddb3d87c65e3741ef434cd2195757fca1302900c1dcfd1687afbdeb6e7e5425a341637292db74baeddb3ddf09650c541c4a509935e236526eef87fc08cab0d14f92eff887700da0d13f3084dc10241ea1259de77a6ab1a744a8ca76d0e653b60f64de60033cf33de62fdb787248e2d73b; dy_swidth=1536; dy_sheight=864; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.6%7D; FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%7D; s_v_web_id=verify_m2lv54up_9vOs50pd_PvFQ_4aIb_8Fc3_PFiGmBYlRcFi; passport_csrf_token=0f8e7f7bafaaf7f809993fb614e11de5; passport_csrf_token_default=0f8e7f7bafaaf7f809993fb614e11de5; WallpaperGuide=%7B%22showTime%22%3A0%2C%22closeTime%22%3A0%2C%22showCount%22%3A0%2C%22cursor1%22%3A10%2C%22cursor2%22%3A2%7D; download_guide=%223%2F20241025%2F1%22; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1536%2C%5C%22screen_height%5C%22%3A864%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A12%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A1.85%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A100%7D%22; strategyABtestKey=%221729927571.632%22; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCTGpTZXl5bEM3eHREWjl1djQwYUJGM2J1RFQ1d3FmSmVIbnhqdHJJSTBpR0M1b0dwTHBqTVdiT0k3cSs0L1ZJLythRVZaRExhL3h2NW9MVHNSQ1FhRms9IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoyfQ%3D%3D; biz_trace_id=80739290; home_can_add_dy_2_desktop=%221%22; xg_device_score=7.478185374092298; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A1%7D%22; IsDouyinActive=true"

**Comment by alphaply** [comment]
cookie不完整

**Comment by moreorlesshub** [comment]
已解决，感谢大佬
