### ISSUE TITLE
请问代码爬取数量太大导致卡住怎么办

### ISSUE THREAD

**Issue by Kamyee0409** [alphaply/DouyinComments#14]
之前试过爬几千条能成功把一级二级都爬下来，但是这次到上万条就卡在二级评论环节不动，时间也没更新。
请问是电脑配置的问题吗？还是数据量过大，超过了目标网站的限制，麻烦解答了！
<img width="662" alt="b85635d16c5a53514cfef56cbc026ab" src="https://github.com/user-attachments/assets/3c76634a-635b-4b66-bfe6-b82385b32464">

**Comment by alphaply** [comment]
尝试使用新的脚本，获取replies，这个脚本允许你中断之后再次运行

**Comment by Kamyee0409** [comment]
> 尝试使用新的脚本，获取replies，这个脚本允许你中断之后再次运行

好的感谢

**Comment by alphaply** [comment]
网页版看看登录状态，更新一下cookie，这样不行，再尝试更换其他账号
