### ISSUE TITLE
二级评论为啥没ip归属地。我看网页都有的，有大佬知道吗？？

### ISSUE THREAD

**Issue by PL-FE** [alphaply/DouyinComments#15]
二级评论为啥没ip归属地。我看网页都有的，有大佬知道吗？？

**Comment by alphaply** [comment]
有具体的视频id么

**Comment by PL-FE** [comment]
已经收到您的来信，我会尽快回复。

**Comment by alphaply** [comment]
增加ip_label即可，稍后进行版本更新

**Comment by PL-FE** [comment]
哥，二级评论那个接口还是没返回。但是网页有`ip_label `这个字段。一级评论是有返回的，就是二次的评论没看到返回这个字段`ip_label `
