### ISSUE TITLE
运行时出现问题

### ISSUE THREAD

**Issue by mkxdpwj** [alphaply/DouyinComments#2]
我直接把代码下载到本地，运行main后程序并没有运行，返回“进程已结束,退出代码-1073741819 (0xC0000005)”，是什么原因呢？

**Comment by alphaply** [comment]
aweme_id = input("aweme_id: ")
cookie = 'your cookie'
main.py中这部分代码自己看readme修改一下

**Comment by mkxdpwj** [comment]
是改了cookie和aweme_id后出现的问题

**Comment by alphaply** [comment]
报错呢？

**Comment by mkxdpwj** [comment]
没有报错，就是不运行，返回“进程已结束,退出代码-1073741819 (0xC0000005)”

**Comment by alphaply** [comment]
？？？？

**Comment by alphaply** [comment]
if __name__ == "__main__":
    asyncio.run(main())
    print('done!')

你怎么运行的？

**Comment by mkxdpwj** [comment]
就是直接运行main.py

**Comment by alphaply** [comment]
pip install httpx pandas PyExecJS

**Comment by mkxdpwj** [comment]
环境装好了

**Comment by alphaply** [comment]
那你加几个print看看有没有打印，没有打印就说明你运行的不对

**Comment by mkxdpwj** [comment]
没打印，该如何运行？

**Comment by alphaply** [comment]
pycharm终端或者cmd（配置好了环境变量）
python main.py

**Comment by mkxdpwj** [comment]
我是用pycharm终端运行的python main.py

**Comment by alphaply** [comment]
python main.py
aweme_id: 
有没有看见aweme_id:

**Comment by alphaply** [comment]
![image](https://github.com/user-attachments/assets/6a83c659-ee0e-4acc-8446-799ee6184872)

**Comment by mkxdpwj** [comment]
没有，我直接if __name__ == "__main__":
    print(1)
    asyncio.run(main())
    print('done!')，都没有东西打印出来

**Comment by alphaply** [comment]
那说明你运行错了

**Comment by mkxdpwj** [comment]
PS D:\DY\DouyinComments-master> python .\main.py
PS D:\DY\DouyinComments-master> 
这样不对吗

**Comment by mkxdpwj** [comment]
aweme_id = '7258913772092296485'
cookie ='...'这里我直接把视频id加进去了

**Comment by alphaply** [comment]
> PS D:\DY\DouyinComments-master> python .\main.py PS D:\DY\DouyinComments-master> 这样不对吗

python版本多少

**Comment by mkxdpwj** [comment]
3.11

**Comment by mkxdpwj** [comment]
它还提示VCS根配置错误：目录 D:\DY\DouyinComments-master 被注册为 Git 根，但在那里没有发现 Git 仓库。 是不是这个原因？

**Comment by alphaply** [comment]
运行之后不要ctrl c等中断运行

**Comment by mkxdpwj** [comment]
没有ctrl c，就等他运行，但一直没运行

**Comment by alphaply** [comment]
一直运行之后，你不要中断，就不会退出进程

**Comment by alphaply** [comment]
抖音接口限制一次接口只能请求50条，你自己看看视频有多少评论

**Comment by mkxdpwj** [comment]
视频评论超过50条就不行了吗

**Comment by alphaply** [comment]
？不是啊，一次请求只能请求50条评论而已啊

**Comment by alphaply** [comment]
1w评论就要请求200次

**Comment by mkxdpwj** [comment]
我感觉不是代码方面的问题，应该是环境方面的问题，我再看看吧

**Comment by alphaply** [comment]
你这个id视频有多少评论？

**Comment by mkxdpwj** [comment]
程序根本就没有运行就返回了

**Comment by mkxdpwj** [comment]
大概8万

**Comment by alphaply** [comment]
那请求就要请求1600次，要很长时间的，不能中断他，要一直跑才行

**Comment by mkxdpwj** [comment]
我没中断，它直接返回了。。。

**Comment by alphaply** [comment]
那就说明你运行的不对啊

**Comment by mkxdpwj** [comment]
但我就是用pycharm终端python main.py呀。。。

**Comment by alphaply** [comment]
![image](https://github.com/user-attachments/assets/3dd20dfa-a279-49de-8c55-051e3ebf25cd)

**Comment by alphaply** [comment]
截图

**Comment by mkxdpwj** [comment]
![image](https://github.com/user-attachments/assets/ba060b78-a8c2-40f1-ae19-3518fa24c3fd)

**Comment by alphaply** [comment]
![image](https://github.com/user-attachments/assets/149ce86e-301c-4bf7-b182-d0842c4f4aa7)

**Comment by mkxdpwj** [comment]
![image](https://github.com/user-attachments/assets/11570cda-2351-4fef-b4a1-cae86f9b7698)

**Comment by alphaply** [comment]
python然后回车看看能进python么

**Comment by mkxdpwj** [comment]
刚刚忘加了

**Comment by alphaply** [comment]
远程吧，我看看

**Comment by mkxdpwj** [comment]
![image](https://github.com/user-attachments/assets/af1e1ede-ce47-4a6b-9283-4139482f644a)

**Comment by mkxdpwj** [comment]
咋远程

**Comment by mkxdpwj** [comment]
要下什么软件是吗

**Comment by alphaply** [comment]
pycharm有code with me么
![image](https://github.com/user-attachments/assets/f058852d-4072-423a-957b-c4eaca930935)

**Comment by alphaply** [comment]
todesk向日葵都可以吧

**Comment by mkxdpwj** [comment]
向日葵吧

**Comment by mkxdpwj** [comment]
等我一下

**Comment by mkxdpwj** [comment]
我的识别码:821721486
使用向日葵即可对我发起远程协助
向日葵下载地址:http://url.oray.com/tGJdas/

**Comment by alphaply** [comment]
没办法编辑

**Comment by mkxdpwj** [comment]
啊？

**Comment by alphaply** [comment]
没法编辑

**Comment by mkxdpwj** [comment]
怎么开编辑

**Comment by alphaply** [comment]
![image](https://github.com/user-attachments/assets/cb68415e-e19e-47cf-a8d8-8e2dd9ae7efc)

**Comment by alphaply** [comment]
允许开键鼠

**Comment by mkxdpwj** [comment]
开了

**Comment by mkxdpwj** [comment]
再来再来

**Comment by alphaply** [comment]
你用todesk吧

**Comment by mkxdpwj** [comment]
没有，我现在下一个吧

**Comment by mkxdpwj** [comment]
等我一下

**Comment by mkxdpwj** [comment]
某科学的pwj邀请您进行远程控制
ToDesk设备代码:475 542 252
临时密码:5rur6fb0
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=koEbNsqOq24hwK112AaBy

**Comment by alphaply** [comment]
那你自己装好再说

**Comment by mkxdpwj** [comment]
好
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests 
重试
  
错误原因


Notifications
Customize
You’re receiving notifications because you authored the thread. 
重试
  
错误原因
2 participants

你没有nodejs
 
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one assigned
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
No branches or pull requests 
重试
  
错误原因


Notifications
Customize
You’re receiving notifications because you authored the thread. 
重试
  
错误原因
2 participants

**Comment by mkxdpwj** [comment]
你来

**Comment by mkxdpwj** [comment]
c
盘要爆了

**Comment by alphaply** [comment]
目前这个爬个几k的评论没啥事情，如果是上w的，抖音他会风控你cookie，所以你要加sleep一下

**Comment by alphaply** [comment]
之前你311的那个python环境有问题，你就用anaconda就行了

**Comment by mkxdpwj** [comment]
好的，所以是编译器问题吗

**Comment by mkxdpwj** [comment]
noodjs是干嘛的呀

**Comment by mkxdpwj** [comment]
我vpn没关，会影响到接口吗

**Comment by alphaply** [comment]
> noodjs是干嘛的呀

跑js获取加密参数用的

**Comment by mkxdpwj** [comment]
搞定了吗？搞定我关远程了，多谢你了

**Comment by alphaply** [comment]
是在跑，时间还是有点久的，我过几天优化一下吧

**Comment by alphaply** [comment]
加个进度条什么的

**Comment by mkxdpwj** [comment]
麻烦你了

**Comment by mkxdpwj** [comment]
跑的久可能是因为我开了vpn

**Comment by alphaply** [comment]
![image](https://github.com/user-attachments/assets/a97feaea-fd90-4bdd-9bca-1a47bfd2b465)

**Comment by alphaply** [comment]
我后面回来再更新吧，顺便看看怎么缓解风控
