### ISSUE TITLE
采集评论区回复的内容不行了,大哥修复下

### ISSUE THREAD

**Issue by xiaosong789** [alphaply/DouyinComments#6]
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by alphaply** [comment]
有具体的id么

**Comment by xiaosong789** [comment]
随便一个视频id都这样
![Uploading (85G{1PYLN9P${[A)9]{ZOD.png…]()

**Comment by alphaply** [comment]
配置正确么

**Comment by xiaosong789** [comment]
正确呀,之前一直用着呢,前几天突然不行的 我加你QQ 你也没有同意

**Comment by alphaply** [comment]
具体的视频id是多少，我复现一下
