### ISSUE TITLE
请问awesome_id在哪里获取

### ISSUE THREAD

**Issue by XXXXBully** [alphaply/DouyinComments#9]

**Comment by alphaply** [comment]
抓包，搜索填comment，看请求参数就是

**Comment by XXXXBully** [comment]
感谢已学会



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月24日(周二) 凌晨1:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [alphaply/DouyinComments] 请问awesome_id在哪里获取 (Issue #9)




 
抓包，搜索填comment，看请求参数就是
